# Generated by Django 6.0.6 on 2026-06-12 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='img',
            field=models.ImageField(null=True, upload_to='models'),
        ),
        migrations.AlterField(
            model_name='main',
            name='job',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
