# Generated by Django 6.0.6 on 2026-06-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_main_img_alter_main_job_alter_main_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media')),
                ('ismi', models.CharField(max_length=1000)),
                ('yoshi', models.CharField(max_length=1000)),
                ('ishi', models.CharField(max_length=1000)),
                ('uzbek', models.CharField(max_length=1000)),
                ('andijon', models.CharField(max_length=1000)),
                ('izboskan', models.CharField(max_length=1000)),
                ('buxoro', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='main',
        ),
    ]
