# Generated by Django 6.0.6 on 2026-06-15 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_edu_delete_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='garahu',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='uroya',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
