# Generated by Django 6.0.6 on 2026-06-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0004_edu_garahu_edu_uroya'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='hiva',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
