# Generated by Django 6.0.6 on 2026-06-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0005_edu_hiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='img1',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
