# Generated by Django 6.0.6 on 2026-06-28 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0006_edu_img1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edu',
            old_name='buxoro',
            new_name='grov',
        ),
        migrations.RenameField(
            model_name='edu',
            old_name='ishi',
            new_name='salom',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='andijon',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='garahu',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='hiva',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='img',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='ismi',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='izboskan',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='uroya',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='uzbek',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='yoshi',
        ),
    ]
