# Generated by Django 6.0.6 on 2026-06-28 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_rename_buxoro_edu_grov_rename_ishi_edu_salom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='img1',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
