# Generated by Django 6.0.6 on 2026-06-29 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_edu_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='uzbek',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
