# Generated by Django 6.0.6 on 2026-06-29 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_edu_uzbek'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='andijon',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='ismi',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='edu',
            name='grov',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='edu',
            name='salom',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
