# Generated by Django 6.0.6 on 2026-07-02 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_edu_andijon_edu_ismi_alter_edu_grov_alter_edu_salom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edu',
            name='img1',
        ),
    ]
