# Generated by Django 6.0.6 on 2026-07-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_remove_edu_img1'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='blocha1',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='blocha2',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='blocha3',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='blocha4',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='blocha5',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='olcha',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
