# Generated by Django 6.0.5 on 2026-07-03 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_edu_blocha1_edu_blocha2_edu_blocha3_edu_blocha4_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edu',
            old_name='blocha2',
            new_name='blch2',
        ),
        migrations.RenameField(
            model_name='edu',
            old_name='blocha3',
            new_name='blcha4',
        ),
        migrations.RenameField(
            model_name='edu',
            old_name='blocha4',
            new_name='bloha3',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='blocha5',
        ),
    ]
