# Generated by Django 6.0.5 on 2026-07-03 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_rename_blocha2_edu_blch2_rename_blocha3_edu_blcha4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='img',
            field=models.ImageField(default=1, unique='', upload_to=''),
            preserve_default=False,
        ),
    ]
