# Generated by Django 6.0.6 on 2026-07-03 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0014_edu_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='img1',
            field=models.ImageField(default=1, unique='', upload_to=''),
            preserve_default=False,
        ),
    ]
