# Generated by Django 6.0.6 on 2026-08-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_edu_img1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edu',
            old_name='grov',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='edu',
            old_name='salom',
            new_name='narxi',
        ),
        migrations.RenameField(
            model_name='edu',
            old_name='uzbek',
            new_name='skidkasi',
        ),
    ]
