# Generated by Django 6.0.6 on 2026-08-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_rename_grov_edu_image_rename_salom_edu_narxi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edu',
            old_name='andijon',
            new_name='tafsifi',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='blch2',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='blcha4',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='blocha1',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='bloha3',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='image',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='img',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='img1',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='ismi',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='olcha',
        ),
    ]
