# Generated by Django 6.0.6 on 2026-08-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_rename_andijon_edu_tafsifi_remove_edu_blch2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='oyiga',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
