# Generated by Django 6.0.5 on 2026-08-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0018_edu_oyiga'),
    ]

    operations = [
        migrations.AddField(
            model_name='edu',
            name='image',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
