# Generated by Django 6.0.5 on 2026-08-12 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0019_edu_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='edu',
            old_name='image',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='edu',
            name='img2',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edu',
            name='img3',
            field=models.ImageField(default=1, upload_to='image'),
            preserve_default=False,
        ),
    ]
