# Generated by Django 6.0.5 on 2026-08-12 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0020_rename_image_edu_img1_edu_img2_edu_img3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edu',
            name='img2',
        ),
        migrations.RemoveField(
            model_name='edu',
            name='img3',
        ),
        migrations.AddField(
            model_name='edu',
            name='bali',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='edu',
            name='sharhlar',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
