# Generated by Django 6.0.5 on 2026-08-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0021_remove_edu_img2_remove_edu_img3_edu_bali_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ligi', models.ImageField(upload_to='media')),
                ('namo', models.CharField(max_length=200)),
                ('tavl', models.CharField(max_length=200)),
                ('nams', models.CharField(max_length=200)),
                ('naml', models.CharField(max_length=200)),
                ('tavf', models.CharField(max_length=200)),
                ('div', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Edu',
        ),
    ]
