# Generated by Django 6.0.6 on 2026-08-23 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0022_kit_delete_edu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kit',
            name='tavf',
        ),
    ]
