# Generated by Django 6.0.6 on 2026-10-09 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0023_remove_kit_tavf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kit',
        ),
    ]
